const calculateButton = document.getElementById("calculateButton");
calculateButton.addEventListener("click", calculateMortgage);

function toggleText() {
  var x = document.getElementById("myText");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}

function calculateMortgage() {
  const monthlyWage = Number(document.getElementById("monthlyWage").value);
  const interestRate = Number(document.getElementById("interestRate").value);
  const monthlyInsurance = Number(document.getElementById("monthlyInsurance").value);
  const propertyPrice = Number(document.getElementById("propertyPrice").value);
  const propertyTaxRate = Number(document.getElementById("propertyTaxRate").value);
  const hoa = Number(document.getElementById("hoa").value);
  const monthlyDebt = Number(document.getElementById("monthlyDebt").value);
  const term = Number(document.getElementById("term").value);
  const otherMonthlyHousingExpense = Number(document.getElementById("otherMonthlyHousing").value);
  const monthlyHOA = Number(document.getElementById("hoa").value);

  if (isNaN(monthlyWage) || isNaN(interestRate) || isNaN(monthlyInsurance) || isNaN(propertyPrice) || isNaN(propertyTaxRate) || isNaN(hoa) || isNaN(monthlyDebt) || isNaN(term)) {
    document.getElementById("result").innerHTML = "Please enter valid numbers for all fields.";
    return;
  }

  const monthlyPropertyTax = (propertyPrice * (propertyTaxRate / 100)) / 12;
  const r = (interestRate / 100) / 12;
  const n = term * 12;
  const w = (monthlyWage * 0.49) - otherMonthlyHousingExpense - hoa - monthlyDebt - monthlyInsurance - monthlyPropertyTax;
  const tio = monthlyPropertyTax + monthlyInsurance + otherMonthlyHousingExpense + monthlyHOA;

  const totalLoanAmountReceivable = w * ((1 - Math.pow(1 + r, -n)) / r);
  const estimatedMonthlyPayment = -w;



  function PMT(rate, nper, pv) {
    return rate * pv / (1 - Math.pow(1 + rate, -nper));
  }

  const comma = (num) => {
    return num.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
  }

  const resultMessage = `
  Estimated Max. Loan Amount $${comma(totalLoanAmountReceivable.toFixed(2))}.
    `;

  const disclaimer = `
    The amount is subject to change depending on the day's interest rate.
    <br>
    <br>
    $${comma(propertyPrice.toFixed(2))} With the interest rate of ${interestRate.toFixed(2)}%,
    <br>
    <br>**With 20% Down Payment ($${comma((propertyPrice * 0.2).toFixed(2))})**
    <br>Your Loan Amount Would Be: $${comma((propertyPrice * 0.8).toFixed(2))}
    <br>Your Monthly Payment Including Property Tax, Insurance, HOA, etc: $${comma((PMT(r, n, (propertyPrice * 0.8)) + tio).toFixed(2))}
    <br>
    <br>**With 25% Down Payment ($${comma((propertyPrice * 0.25).toFixed(2))})**
    <br>Your Loan Amount Would Be: $${comma((propertyPrice * 0.75).toFixed(2))}
    <br>Your Monthly Payment Including Property Tax, Insurance, HOA, etc: $${comma((PMT(r, n, (propertyPrice * 0.75)) + tio).toFixed(2))}
    <br>
    <br>**With 30% Down Payment ($${comma((propertyPrice * 0.3).toFixed(2))})**
    <br>Your Loan Amount Would Be: $${comma((propertyPrice * 0.7).toFixed(2))}
    <br>Your Monthly Payment Including Property Tax, Insurance, HOA, etc: $${comma((PMT(r, n, (propertyPrice * 0.7)) + tio).toFixed(2))}
    <br>
    <br>**With 40% Down Payment ($${comma((propertyPrice * 0.4).toFixed(2))})**
    <br>Your Loan Amount Would Be: $${comma((propertyPrice * 0.6).toFixed(2))}
    <br>Your Monthly Payment Including Property Tax, Insurance, HOA, etc: $${comma((PMT(r, n, (propertyPrice * 0.6)) + tio).toFixed(2))}
    <br>
    <br>**With 50% Down Payment ($${comma((propertyPrice * 0.5).toFixed(2))})**
    <br>Your Loan Amount Would Be: $${comma((propertyPrice * 0.5).toFixed(2))}
    <br>Your Monthly Payment Including Property Tax, Insurance, HOA, etc: $${comma((PMT(r, n, (propertyPrice * 0.5)) + tio).toFixed(2))}
    <br>
    <br>**With 60% Down Payment ($${comma((propertyPrice * 0.6).toFixed(2))})**
    <br>Your Loan Amount Would Be: $${comma((propertyPrice * 0.4).toFixed(2))}
    <br>Your Monthly Payment Including Property Tax, Insurance, HOA, etc: $${comma((PMT(r, n, (propertyPrice * 0.4)) + tio).toFixed(2))}
    <br>
    <br>**With 80% Down Payment ($${comma((propertyPrice * 0.8).toFixed(2))})**
    <br>Your Loan Amount Would Be: $${comma((propertyPrice * 0.2).toFixed(2))}
    <br>Your Monthly Payment Including Property Tax, Insurance, HOA, etc: $${comma((PMT(r, n, (propertyPrice * 0.2)) + tio).toFixed(2))}
    <br> These Are Just Estimations Generated by Using Math Equations.
    <br>
    <br>
    Disclaimer: If Down Payment is Less Than 20%,<br> Total Loan Amount Could Decrease Due to Mortgage Insurance.
      `;

  document.getElementById("result").innerHTML = resultMessage;
  document.getElementById("disclaimer").innerHTML = disclaimer;
}
